# Generated by Django 3.1.7 on 2021-03-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
